spring:
  datasource:
    url: jdbc:sqlserver://springazure.database.windows.net:1433;database=BYDB;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;authentication=ActiveDirectoryPassword
    username: CloudSA4594e38d
    password: Thanesh@0810
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9999


